export const mathSymbols = [
  // Basic Maths
  { latex: "\\frac{a}{b}", symbol: "a/b", category: "Basic Maths" },
  { latex: "\\sqrt{x}", symbol: "√x", category: "Basic Maths" },
  { latex: "\\pm", symbol: "±", category: "Basic Maths" },
  { latex: "\\mp", symbol: "∓", category: "Basic Maths" },
  { latex: "\\times", symbol: "×", category: "Basic Maths" },
  { latex: "\\div", symbol: "÷", category: "Basic Maths" },
  { latex: "\\cdot", symbol: "⋅", category: "Basic Maths" },
  { latex: "\\ast", symbol: "*", category: "Basic Maths" },
  { latex: "\\star", symbol: "★", category: "Basic Maths" },
  { latex: "\\triangle", symbol: "△", category: "Basic Maths" },
  { latex: "\\boxed{a}", symbol: "Boxed", category: "Basic Maths" },
  { latex: "\\pm", symbol: "±", category: "Basic Maths" },
  { latex: "\\div", symbol: "÷", category: "Basic Maths" },
  { latex: "\\times", symbol: "×", category: "Basic Maths" },
  { latex: "\\sqrt{x}", symbol: "√x", category: "Basic Maths" },
  { latex: "\\frac{a}{b}", symbol: "a/b", category: "Basic Maths" },
  { latex: "\\sum_{i=1}^{n} i", symbol: "∑_i=1^n i", category: "Basic Maths" },
  { latex: "\\prod_{i=1}^{n} i", symbol: "∏_i=1^n i", category: "Basic Maths" },
  {
    latex: "\\int_{a}^{b} f(x) \\, dx",
    symbol: "∫_a^b f(x) dx",
    category: "Basic Maths",
  },
  { latex: "\\leq", symbol: "≤", category: "Basic Maths" },
  { latex: "\\geq", symbol: "≥", category: "Basic Maths" },
  { latex: "\\neq", symbol: "≠", category: "Basic Maths" },
  { latex: "\\approx", symbol: "≈", category: "Basic Maths" },
  { latex: "\\rightarrow", symbol: "→", category: "Basic Maths" },
  { latex: "\\leftarrow", symbol: "←", category: "Basic Maths" },
  { latex: "\\leftrightarrow", symbol: "↔", category: "Basic Maths" },
  { latex: "\\infty", symbol: "∞", category: "Basic Maths" },
  { latex: "\\notin", symbol: "∉", category: "Basic Maths" },
  { latex: "\\subseteq", symbol: "⊆", category: "Basic Maths" },
  { latex: "\\supseteq", symbol: "⊇", category: "Basic Maths" },
  { latex: "\\cup", symbol: "∪", category: "Basic Maths" },
  { latex: "\\cap", symbol: "∩", category: "Basic Maths" },
  { latex: "\\angle", symbol: "∠", category: "Basic Maths" },
  { latex: "\\emptyset", symbol: "∅", category: "Basic Maths" },
  { latex: "\\sqrt[n]{x}", symbol: "√[n]{x}", category: "Basic Maths" },
  { latex: "\\text{log}_b(x)", symbol: "log_b(x)", category: "Basic Maths" },
  { latex: "\\text{ln}(x)", symbol: "ln(x)", category: "Basic Maths" },
  { latex: "\\lceil x \\rceil", symbol: "⌈x⌉", category: "Basic Maths" },
  { latex: "\\lfloor x \\rfloor", symbol: "⌊x⌋", category: "Basic Maths" },

  // Relations
  { latex: "\\le", symbol: "≤", category: "Relations" },
  { latex: "\\ge", symbol: "≥", category: "Relations" },
  { latex: "\\neq", symbol: "≠", category: "Relations" },
  { latex: "\\sim", symbol: "∼", category: "Relations" },
  { latex: "\\ll", symbol: "≪", category: "Relations" },
  { latex: "\\gg", symbol: "≫", category: "Relations" },
  { latex: "\\doteq", symbol: "≒", category: "Relations" },
  { latex: "\\simeq", symbol: "≃", category: "Relations" },
  { latex: "\\subset", symbol: "⊂", category: "Relations" },
  { latex: "\\supset", symbol: "⊃", category: "Relations" },
  { latex: "\\approx", symbol: "≈", category: "Relations" },
  { latex: "\\asymp", symbol: "≍", category: "Relations" },
  { latex: "\\subseteq", symbol: "⊆", category: "Relations" },
  { latex: "\\supseteq", symbol: "⊇", category: "Relations" },
  { latex: "\\cong", symbol: "≅", category: "Relations" },
  { latex: "\\smile", symbol: "⌣", category: "Relations" },
  { latex: "\\sqsubset", symbol: "⊏", category: "Relations" },
  { latex: "\\sqsupset", symbol: "⊐", category: "Relations" },
  { latex: "\\equiv", symbol: "≡", category: "Relations" },
  { latex: "\\frown", symbol: "⌢", category: "Relations" },
  { latex: "\\sqsubseteq", symbol: "⊑", category: "Relations" },
  { latex: "\\sqsupseteq", symbol: "⊒", category: "Relations" },
  { latex: "\\propto", symbol: "∝", category: "Relations" },
  { latex: "\\bowtie", symbol: "⋈", category: "Relations" },
  { latex: "\\in", symbol: "∈", category: "Relations" },
  { latex: "\\ni", symbol: "∋", category: "Relations" },
  { latex: "\\prec", symbol: "≺", category: "Relations" },
  { latex: "\\succ", symbol: "≻", category: "Relations" },
  { latex: "\\vdash", symbol: "⊢", category: "Relations" },
  { latex: "\\dashv", symbol: "⊣", category: "Relations" },
  { latex: "\\preceq", symbol: "≼", category: "Relations" },
  { latex: "\\succeq", symbol: "≽", category: "Relations" },
  { latex: "\\models", symbol: "⊧", category: "Relations" },
  { latex: "\\perp", symbol: "⊥", category: "Relations" },
  { latex: "\\parallel", symbol: "∥", category: "Relations" },
  { latex: "\\mid", symbol: "∣", category: "Relations" },
  { latex: "\\bumpeq", symbol: "≎", category: "Relations" },
  { latex: "\\nmid", symbol: "∤", category: "Relations" },
  { latex: "\\nleq", symbol: "≰", category: "Relations" },
  { latex: "\\ngeq", symbol: "≱", category: "Relations" },
  { latex: "\\nsim", symbol: "≁", category: "Relations" },
  { latex: "\\ncong", symbol: "≇", category: "Relations" },
  { latex: "\\nparallel", symbol: "∦", category: "Relations" },
  { latex: "\\not<", symbol: "≮", category: "Relations" },
  { latex: "\\not>", symbol: "≯", category: "Relations" },
  { latex: "\\not=", symbol: "≠", category: "Relations" },
  { latex: "\\not\\le", symbol: "≮", category: "Relations" },
  { latex: "\\not\\ge", symbol: "≯", category: "Relations" },
  { latex: "\\not\\sim", symbol: "≁", category: "Relations" },
  { latex: "\\not\\approx", symbol: "≉", category: "Relations" },
  { latex: "\\not\\cong", symbol: "≇", category: "Relations" },
  { latex: "\\not\\equiv", symbol: "≢", category: "Relations" },
  { latex: "\\not\\parallel", symbol: "∦", category: "Relations" },
  { latex: "\\nless", symbol: "≮", category: "Relations" },
  { latex: "\\ngtr", symbol: "≯", category: "Relations" },
  { latex: "\\lneq", symbol: "≨", category: "Relations" },
  { latex: "\\gneq", symbol: "≩", category: "Relations" },
  { latex: "\\lnsim", symbol: "⋪", category: "Relations" },
  { latex: "\\lneqq", symbol: "≨", category: "Relations" },
  { latex: "\\gneqq", symbol: "≩", category: "Relations" },

  // Greek Letters
  { latex: "\\alpha", symbol: "α", category: "Greek Letters" },
  { latex: "\\beta", symbol: "β", category: "Greek Letters" },
  { latex: "\\gamma", symbol: "γ", category: "Greek Letters" },
  { latex: "\\delta", symbol: "δ", category: "Greek Letters" },
  { latex: "\\epsilon", symbol: "ε", category: "Greek Letters" },
  { latex: "\\varepsilon", symbol: "ϵ", category: "Greek Letters" },
  { latex: "\\zeta", symbol: "ζ", category: "Greek Letters" },
  { latex: "\\eta", symbol: "η", category: "Greek Letters" },
  { latex: "\\theta", symbol: "θ", category: "Greek Letters" },
  { latex: "\\vartheta", symbol: "ϑ", category: "Greek Letters" },
  { latex: "\\iota", symbol: "ι", category: "Greek Letters" },
  { latex: "\\kappa", symbol: "κ", category: "Greek Letters" },
  { latex: "\\lambda", symbol: "λ", category: "Greek Letters" },
  { latex: "\\mu", symbol: "μ", category: "Greek Letters" },
  { latex: "\\nu", symbol: "ν", category: "Greek Letters" },
  { latex: "\\xi", symbol: "ξ", category: "Greek Letters" },
  { latex: "\\pi", symbol: "π", category: "Greek Letters" },
  { latex: "\\varpi", symbol: "ϖ", category: "Greek Letters" },
  { latex: "\\rho", symbol: "ρ", category: "Greek Letters" },
  { latex: "\\varrho", symbol: "ϱ", category: "Greek Letters" },
  { latex: "\\sigma", symbol: "σ", category: "Greek Letters" },
  { latex: "\\varsigma", symbol: "ς", category: "Greek Letters" },
  { latex: "\\tau", symbol: "τ", category: "Greek Letters" },
  { latex: "\\upsilon", symbol: "υ", category: "Greek Letters" },
  { latex: "\\phi", symbol: "φ", category: "Greek Letters" },
  { latex: "\\varphi", symbol: "ϕ", category: "Greek Letters" },
  { latex: "\\chi", symbol: "χ", category: "Greek Letters" },
  { latex: "\\psi", symbol: "ψ", category: "Greek Letters" },
  { latex: "\\omega", symbol: "ω", category: "Greek Letters" },
  { latex: "\\Gamma", symbol: "Γ", category: "Greek Letters" },
  { latex: "\\Delta", symbol: "Δ", category: "Greek Letters" },
  { latex: "\\Theta", symbol: "Θ", category: "Greek Letters" },
  { latex: "\\Lambda", symbol: "Λ", category: "Greek Letters" },
  { latex: "\\Xi", symbol: "Ξ", category: "Greek Letters" },
  { latex: "\\Pi", symbol: "Π", category: "Greek Letters" },
  { latex: "\\Sigma", symbol: "Σ", category: "Greek Letters" },
  { latex: "\\Upsilon", symbol: "Υ", category: "Greek Letters" },
  { latex: "\\Phi", symbol: "Φ", category: "Greek Letters" },
  { latex: "\\Psi", symbol: "Ψ", category: "Greek Letters" },
  { latex: "\\Omega", symbol: "Ω", category: "Greek Letters" },

  // Operators
  { latex: "\\pm", symbol: "±", category: "Operators" },
  { latex: "\\mp", symbol: "∓", category: "Operators" },
  { latex: "\\times", symbol: "×", category: "Operators" },
  { latex: "\\div", symbol: "÷", category: "Operators" },
  { latex: "\\cdot", symbol: "⋅", category: "Operators" },
  { latex: "\\ast", symbol: "*", category: "Operators" },
  { latex: "\\star", symbol: "★", category: "Operators" },
  { latex: "\\dagger", symbol: "†", category: "Operators" },
  { latex: "\\ddagger", symbol: "‡", category: "Operators" },
  { latex: "\\amalg", symbol: "⨿", category: "Operators" },
  { latex: "\\cap", symbol: "∩", category: "Operators" },
  { latex: "\\cup", symbol: "∪", category: "Operators" },
  { latex: "\\uplus", symbol: "⊎", category: "Operators" },
  { latex: "\\sqcap", symbol: "⊓", category: "Operators" },
  { latex: "\\sqcup", symbol: "⊔", category: "Operators" },
  { latex: "\\vee", symbol: "∨", category: "Operators" },
  { latex: "\\wedge", symbol: "∧", category: "Operators" },
  { latex: "\\oplus", symbol: "⊕", category: "Operators" },
  { latex: "\\ominus", symbol: "⊖", category: "Operators" },
  { latex: "\\otimes", symbol: "⊗", category: "Operators" },
  { latex: "\\circ", symbol: "∘", category: "Operators" },
  { latex: "\\bullet", symbol: "•", category: "Operators" },
  { latex: "\\diamond", symbol: "♦", category: "Operators" },
  { latex: "\\lhd", symbol: "⊲", category: "Operators" },
  { latex: "\\rhd", symbol: "⊳", category: "Operators" },
  { latex: "\\unlhd", symbol: "⩹", category: "Operators" },
  { latex: "\\unrhd", symbol: "⩺", category: "Operators" },
  { latex: "\\oslash", symbol: "⊘", category: "Operators" },
  { latex: "\\odot", symbol: "⊙", category: "Operators" },
  { latex: "\\bigcirc", symbol: "◯", category: "Operators" },
  { latex: "\\triangleleft", symbol: "⊲", category: "Operators" },
  { latex: "\\Diamond", symbol: "♦", category: "Operators" },
  { latex: "\\bigtriangleup", symbol: "△", category: "Operators" },
  { latex: "\\bigtriangledown", symbol: "▽", category: "Operators" },
  { latex: "\\Box", symbol: "□", category: "Operators" },
  { latex: "\\triangleright", symbol: "⊳", category: "Operators" },
  { latex: "\\setminus", symbol: "∖", category: "Operators" },
  { latex: "\\wr", symbol: "≀", category: "Operators" },
  { latex: "\\sqrt{x}", symbol: "√x", category: "Operators" },
  { latex: "x^{\\circ}", symbol: "x⁰", category: "Operators" },
  { latex: "\\triangledown", symbol: "▿", category: "Operators" },
  { latex: "\\sqrt[n]{x}", symbol: "√[n]{x}", category: "Operators" },
  { latex: "a^x", symbol: "aˣ", category: "Operators" },
  { latex: "a^{xyz}", symbol: "a^{xyz}", category: "Operators" },
  { latex: "a_x", symbol: "aₓ", category: "Operators" },

  // Arrows
  { latex: "\\gets", symbol: "←", category: "Arrows" },
  { latex: "\\to", symbol: "→", category: "Arrows" },
  { latex: "\\leftarrow", symbol: "←", category: "Arrows" },
  { latex: "\\Leftarrow", symbol: "⇐", category: "Arrows" },
  { latex: "\\rightarrow", symbol: "→", category: "Arrows" },
  { latex: "\\Rightarrow", symbol: "⇒", category: "Arrows" },
  { latex: "\\leftrightarrow", symbol: "↔", category: "Arrows" },
  { latex: "\\Leftrightarrow", symbol: "⇔", category: "Arrows" },
  { latex: "\\mapsto", symbol: "↦", category: "Arrows" },
  { latex: "\\hookleftarrow", symbol: "↩", category: "Arrows" },
  { latex: "\\leftharpoonup", symbol: "↿", category: "Arrows" },
  { latex: "\\leftharpoondown", symbol: "↽", category: "Arrows" },
  { latex: "\\rightleftharpoons", symbol: "⇌", category: "Arrows" },
  { latex: "\\longleftarrow", symbol: "⟵", category: "Arrows" },
  { latex: "\\Longleftarrow", symbol: "⟸", category: "Arrows" },
  { latex: "\\longrightarrow", symbol: "⟶", category: "Arrows" },
  { latex: "\\Longrightarrow", symbol: "⟹", category: "Arrows" },
  { latex: "\\longleftrightarrow", symbol: "⟷", category: "Arrows" },
  { latex: "\\Longleftrightarrow", symbol: "⟺", category: "Arrows" },
  { latex: "\\longmapsto", symbol: "⟼", category: "Arrows" },
  { latex: "\\hookrightarrow", symbol: "↪", category: "Arrows" },
  { latex: "\\rightharpoonup", symbol: "⇀", category: "Arrows" },
  { latex: "\\rightharpoondown", symbol: "⇁", category: "Arrows" },
  { latex: "\\leadsto", symbol: "↝", category: "Arrows" },
  { latex: "\\uparrow", symbol: "↑", category: "Arrows" },
  { latex: "\\Uparrow", symbol: "⇑", category: "Arrows" },
  { latex: "\\downarrow", symbol: "↓", category: "Arrows" },
  { latex: "\\Downarrow", symbol: "⇓", category: "Arrows" },
  { latex: "\\updownarrow", symbol: "↕", category: "Arrows" },
  { latex: "\\Updownarrow", symbol: "⇕", category: "Arrows" },
  { latex: "\\nearrow", symbol: "↗", category: "Arrows" },
  { latex: "\\searrow", symbol: "↘", category: "Arrows" },
  { latex: "\\swarrow", symbol: "↙", category: "Arrows" },
  { latex: "\\nwarrow", symbol: "↖", category: "Arrows" },
  { latex: "\\overrightarrow{AB}", symbol: "→AB", category: "Arrows" },
  { latex: "\\overleftarrow{AB}", symbol: "←AB", category: "Arrows" },
  { latex: "\\overleftrightarrow{AB}", symbol: "↔AB", category: "Arrows" },
  // Geometry
  { latex: "\\triangle", symbol: "△", category: "Geometry" },
  { latex: "\\angle", symbol: "∠", category: "Geometry" },
  { latex: "\\parallel", symbol: "∥", category: "Geometry" },
  { latex: "\\perp", symbol: "⊥", category: "Geometry" },
  { latex: "\\circ", symbol: "∘", category: "Geometry" },
  { latex: "\\cong", symbol: "≅", category: "Geometry" },
  { latex: "\\therefore", symbol: "∴", category: "Geometry" },
  { latex: "\\because", symbol: "∵", category: "Geometry" },
  { latex: "\\measuredangle", symbol: "∡", category: "Geometry" },
  { latex: "\\mid", symbol: "∣", category: "Geometry" },
  { latex: "\\bot", symbol: "⊥", category: "Geometry" },
  { latex: "\\nparallel", symbol: "∦", category: "Geometry" },
  { latex: "\\perp", symbol: "⊥", category: "Geometry" },
  { latex: "\\square", symbol: "□", category: "Geometry" },
  { latex: "\\blacksquare", symbol: "■", category: "Geometry" },
  // { latex: "\\hexagon", symbol: "⬡", category: "Geometry" },
  { latex: "\\triangleq", symbol: "≜", category: "Geometry" },
  { latex: "\\mid", symbol: "∣", category: "Geometry" },
  { latex: "\\langle", symbol: "⟨", category: "Geometry" },
  { latex: "\\rangle", symbol: "⟩", category: "Geometry" },

  // Structures
  {
    latex: "\\int_{a}^{b} f(x) \\, dx",
    symbol: "∫_a^b f(x) dx",
    category: "Structures",
  },
  { latex: "\\sum_{i=1}^{n} i", symbol: "∑_i=1^n i", category: "Structures" },
  { latex: "\\prod_{i=1}^{n} i", symbol: "∏_i=1^n i", category: "Structures" },
  {
    latex: "\\lim_{x \\to \\infty} f(x)",
    symbol: "lim_{x → ∞} f(x)",
    category: "Structures",
  },
  { latex: "\\frac{a}{b}", symbol: "a/b", category: "Structures" },
  { latex: "\\sqrt[n]{x}", symbol: "√[n]{x}", category: "Structures" },
  { latex: "\\binom{n}{k}", symbol: "C(n, k)", category: "Structures" },
  { latex: "\\text{det}(A)", symbol: "det(A)", category: "Structures" },
  { latex: "\\langle a, b \\rangle", symbol: "⟨a, b⟩", category: "Structures" },
  { latex: "\\lbrace a, b \\rbrace", symbol: "{a, b}", category: "Structures" },
  { latex: "\\angle ABC", symbol: "∠ABC", category: "Structures" },
  { latex: "\\overline{AB}", symbol: "¯AB", category: "Structures" },
  { latex: "\\triangle ABC", symbol: "△ABC", category: "Structures" },
  { latex: "\\oplus", symbol: "⊕", category: "Structures" },
  { latex: "\\otimes", symbol: "⊗", category: "Structures" },
  { latex: "\\cup", symbol: "∪", category: "Structures" },
  { latex: "\\cap", symbol: "∩", category: "Structures" },
  { latex: "\\in", symbol: "∈", category: "Structures" },
  { latex: "\\notin", symbol: "∉", category: "Structures" },
  { latex: "\\subset", symbol: "⊂", category: "Structures" },
  { latex: "\\supset", symbol: "⊃", category: "Structures" },

  // Add more symbols as needed
];
