export const mathSymbols = [
  // Basic Maths (expanded)
  { latex: "+", category: "Basic Maths" },
  { latex: "-", category: "Basic Maths" },
  { latex: "=", category: "Basic Maths" },
  { latex: "<", category: "Basic Maths" },
  { latex: ">", category: "Basic Maths" },
  { latex: ":", category: "Basic Maths" },
  { latex: "\\overline{A}", category: "Basic Maths" },
  { latex: "\\overline{a}", category: "Basic Maths" },
  { latex: "\\mp", category: "Basic Maths" },
  { latex: "\\times", category: "Basic Maths" },
  { latex: "\\div", category: "Basic Maths" },
  { latex: "\\cdot", category: "Basic Maths" },
  { latex: "\\ast", category: "Basic Maths" },
  { latex: "\\star", category: "Basic Maths" },
  { latex: "\\triangle", category: "Basic Maths" },
  { latex: "\\boxed{a}", category: "Basic Maths" },
  { latex: "\\pm", category: "Basic Maths" },
  { latex: "\\sqrt{x}", category: "Basic Maths" },
  { latex: "\\frac{a}{b}", category: "Basic Maths" },
  { latex: "\\sum_{i=1}^{n} i", category: "Basic Maths" },
  { latex: "\\prod_{i=1}^{n} i", category: "Basic Maths" },
  { latex: "\\int_{a}^{b} f(x) \\, dx", category: "Basic Maths" },
  { latex: "\\leq", category: "Basic Maths" },
  { latex: "\\geq", category: "Basic Maths" },
  { latex: "\\neq", category: "Basic Maths" },
  { latex: "\\approx", category: "Basic Maths" },
  { latex: "\\rightarrow", category: "Basic Maths" },
  { latex: "\\leftarrow", category: "Basic Maths" },
  { latex: "\\leftrightarrow", category: "Basic Maths" },
  { latex: "\\infty", category: "Basic Maths" },
  { latex: "\\in", category: "Basic Maths" },
  { latex: "\\notin", category: "Basic Maths" },
  { latex: "\\subseteq", category: "Basic Maths" },
  { latex: "\\supseteq", category: "Basic Maths" },
  { latex: "\\cup", category: "Basic Maths" },
  { latex: "\\cap", category: "Basic Maths" },
  { latex: "\\angle", category: "Basic Maths" },
  { latex: "\\emptyset", category: "Basic Maths" },
  { latex: "\\sqrt[n]{x}", category: "Basic Maths" },
  { latex: "\\log_b(x)", category: "Basic Maths" },
  { latex: "\\ln(x)", category: "Basic Maths" },
  { latex: "\\lceil x \\rceil", category: "Basic Maths" },
  { latex: "\\lfloor x \\rfloor", category: "Basic Maths" },
  { latex: "x^2", category: "Basic Maths" },
  { latex: "x^{n}", category: "Basic Maths" },
  { latex: "x_i", category: "Basic Maths" },
  { latex: "\\partial", category: "Basic Maths" },
  { latex: "\\nabla", category: "Basic Maths" },
  { latex: "\\hbar", category: "Basic Maths" },
  { latex: "\\imath", category: "Basic Maths" },
  { latex: "\\jmath", category: "Basic Maths" },
  { latex: "\\ell", category: "Basic Maths" },
  { latex: "\\Re", category: "Basic Maths" },
  { latex: "\\Im", category: "Basic Maths" },
  { latex: "\\wp", category: "Basic Maths" },

  // Relations (expanded)
  { latex: "\\le", category: "Relations" },
  { latex: "\\ge", category: "Relations" },
  { latex: "\\neq", category: "Relations" },
  { latex: "\\sim", category: "Relations" },
  { latex: "\\ll", category: "Relations" },
  { latex: "\\gg", category: "Relations" },
  { latex: "\\doteq", category: "Relations" },
  { latex: "\\simeq", category: "Relations" },
  { latex: "\\subset", category: "Relations" },
  { latex: "\\supset", category: "Relations" },
  { latex: "\\approx", category: "Relations" },
  { latex: "\\asymp", category: "Relations" },
  { latex: "\\subseteq", category: "Relations" },
  { latex: "\\supseteq", category: "Relations" },
  { latex: "\\cong", category: "Relations" },
  { latex: "\\equiv", category: "Relations" },
  { latex: "\\propto", category: "Relations" },
  { latex: "\\in", category: "Relations" },
  { latex: "\\ni", category: "Relations" },
  { latex: "\\prec", category: "Relations" },
  { latex: "\\succ", category: "Relations" },
  { latex: "\\preceq", category: "Relations" },
  { latex: "\\succeq", category: "Relations" },
  { latex: "\\perp", category: "Relations" },
  { latex: "\\parallel", category: "Relations" },
  { latex: "\\mid", category: "Relations" },
  { latex: "\\nmid", category: "Relations" },
  { latex: "\\models", category: "Relations" },
  { latex: "\\bowtie", category: "Relations" },
  { latex: "\\Join", category: "Relations" },
  { latex: "\\smile", category: "Relations" },
  { latex: "\\frown", category: "Relations" },
  { latex: "\\vdash", category: "Relations" },
  { latex: "\\dashv", category: "Relations" },
  { latex: "\\Vdash", category: "Relations" },
  { latex: "\\nVdash", category: "Relations" },

  // Greek Letters (complete)
  { latex: "\\alpha", category: "Greek Letters" },
  { latex: "\\beta", category: "Greek Letters" },
  { latex: "\\gamma", category: "Greek Letters" },
  { latex: "\\delta", category: "Greek Letters" },
  { latex: "\\epsilon", category: "Greek Letters" },
  { latex: "\\varepsilon", category: "Greek Letters" },
  { latex: "\\zeta", category: "Greek Letters" },
  { latex: "\\eta", category: "Greek Letters" },
  { latex: "\\theta", category: "Greek Letters" },
  { latex: "\\vartheta", category: "Greek Letters" },
  { latex: "\\iota", category: "Greek Letters" },
  { latex: "\\kappa", category: "Greek Letters" },
  { latex: "\\lambda", category: "Greek Letters" },
  { latex: "\\mu", category: "Greek Letters" },
  { latex: "\\nu", category: "Greek Letters" },
  { latex: "\\xi", category: "Greek Letters" },
  { latex: "\\pi", category: "Greek Letters" },
  { latex: "\\varpi", category: "Greek Letters" },
  { latex: "\\rho", category: "Greek Letters" },
  { latex: "\\varrho", category: "Greek Letters" },
  { latex: "\\sigma", category: "Greek Letters" },
  { latex: "\\varsigma", category: "Greek Letters" },
  { latex: "\\tau", category: "Greek Letters" },
  { latex: "\\upsilon", category: "Greek Letters" },
  { latex: "\\phi", category: "Greek Letters" },
  { latex: "\\varphi", category: "Greek Letters" },
  { latex: "\\chi", category: "Greek Letters" },
  { latex: "\\psi", category: "Greek Letters" },
  { latex: "\\omega", category: "Greek Letters" },
  { latex: "\\Gamma", category: "Greek Letters" },
  { latex: "\\Delta", category: "Greek Letters" },
  { latex: "\\Theta", category: "Greek Letters" },
  { latex: "\\Lambda", category: "Greek Letters" },
  { latex: "\\Xi", category: "Greek Letters" },
  { latex: "\\Pi", category: "Greek Letters" },
  { latex: "\\Sigma", category: "Greek Letters" },
  { latex: "\\Upsilon", category: "Greek Letters" },
  { latex: "\\Phi", category: "Greek Letters" },
  { latex: "\\Psi", category: "Greek Letters" },
  { latex: "\\Omega", category: "Greek Letters" },

  // Operators (expanded)
  { latex: "\\pm", category: "Operators" },
  { latex: "\\mp", category: "Operators" },
  { latex: "\\times", category: "Operators" },
  { latex: "\\div", category: "Operators" },
  { latex: "\\cdot", category: "Operators" },
  { latex: "\\ast", category: "Operators" },
  { latex: "\\star", category: "Operators" },
  { latex: "\\dagger", category: "Operators" },
  { latex: "\\ddagger", category: "Operators" },
  { latex: "\\cap", category: "Operators" },
  { latex: "\\cup", category: "Operators" },
  { latex: "\\vee", category: "Operators" },
  { latex: "\\wedge", category: "Operators" },
  { latex: "\\oplus", category: "Operators" },
  { latex: "\\ominus", category: "Operators" },
  { latex: "\\otimes", category: "Operators" },
  { latex: "\\oslash", category: "Operators" },
  { latex: "\\odot", category: "Operators" },
  { latex: "\\circ", category: "Operators" },
  { latex: "\\bullet", category: "Operators" },
  { latex: "\\diamond", category: "Operators" },
  { latex: "\\setminus", category: "Operators" },
  { latex: "\\wr", category: "Operators" },
  { latex: "\\amalg", category: "Operators" },
  { latex: "\\bigcirc", category: "Operators" },
  { latex: "\\bigtriangleup", category: "Operators" },
  { latex: "\\bigtriangledown", category: "Operators" },
  { latex: "\\uplus", category: "Operators" },
  { latex: "\\sqcap", category: "Operators" },
  { latex: "\\sqcup", category: "Operators" },

  // Arrows (expanded)
  { latex: "\\leftarrow", category: "Arrows" },
  { latex: "\\Leftarrow", category: "Arrows" },
  { latex: "\\rightarrow", category: "Arrows" },
  { latex: "\\Rightarrow", category: "Arrows" },
  { latex: "\\leftrightarrow", category: "Arrows" },
  { latex: "\\Leftrightarrow", category: "Arrows" },
  { latex: "\\mapsto", category: "Arrows" },
  { latex: "\\longleftarrow", category: "Arrows" },
  { latex: "\\Longleftarrow", category: "Arrows" },
  { latex: "\\longrightarrow", category: "Arrows" },
  { latex: "\\Longrightarrow", category: "Arrows" },
  { latex: "\\longleftrightarrow", category: "Arrows" },
  { latex: "\\Longleftrightarrow", category: "Arrows" },
  { latex: "\\uparrow", category: "Arrows" },
  { latex: "\\Uparrow", category: "Arrows" },
  { latex: "\\downarrow", category: "Arrows" },
  { latex: "\\Downarrow", category: "Arrows" },
  { latex: "\\updownarrow", category: "Arrows" },
  { latex: "\\Updownarrow", category: "Arrows" },
  { latex: "\\nearrow", category: "Arrows" },
  { latex: "\\searrow", category: "Arrows" },
  { latex: "\\swarrow", category: "Arrows" },
  { latex: "\\nwarrow", category: "Arrows" },
  { latex: "\\hookleftarrow", category: "Arrows" },
  { latex: "\\hookrightarrow", category: "Arrows" },
  { latex: "\\leftharpoonup", category: "Arrows" },
  { latex: "\\leftharpoondown", category: "Arrows" },
  { latex: "\\rightharpoonup", category: "Arrows" },
  { latex: "\\rightharpoondown", category: "Arrows" },
  { latex: "\\rightleftharpoons", category: "Arrows" },
  { latex: "\\leadsto", category: "Arrows" },

  // Geometry (expanded)
  { latex: "\\triangle", category: "Geometry" },
  { latex: "\\angle", category: "Geometry" },
  { latex: "\\parallel", category: "Geometry" },
  { latex: "\\perp", category: "Geometry" },
  { latex: "\\circ", category: "Geometry" },
  { latex: "\\cong", category: "Geometry" },
  { latex: "\\therefore", category: "Geometry" },
  { latex: "\\because", category: "Geometry" },
  { latex: "\\square", category: "Geometry" },
  { latex: "\\blacksquare", category: "Geometry" },
  { latex: "\\langle", category: "Geometry" },
  { latex: "\\rangle", category: "Geometry" },
  { latex: "\\diamond", category: "Geometry" },
  { latex: "\\measuredangle", category: "Geometry" },
  { latex: "\\sphericalangle", category: "Geometry" },
  { latex: "\\triangleleft", category: "Geometry" },
  { latex: "\\triangleright", category: "Geometry" },
  { latex: "\\bigtriangleup", category: "Geometry" },
  { latex: "\\bigtriangledown", category: "Geometry" },

  // Structures (expanded)
  { latex: "\\int_{a}^{b} f(x) \\, dx", category: "Structures" },
  { latex: "\\sum_{i=1}^{n} i", category: "Structures" },
  { latex: "\\prod_{i=1}^{n} i", category: "Structures" },
  { latex: "\\lim_{x \\to \\infty} f(x)", category: "Structures" },
  { latex: "\\frac{a}{b}", category: "Structures" },
  { latex: "\\sqrt[n]{x}", category: "Structures" },
  { latex: "\\binom{n}{k}", category: "Structures" },
  { latex: "\\det(A)", category: "Structures" },
  { latex: "\\langle a, b \\rangle", category: "Structures" },
  { latex: "\\{a, b\\}", category: "Structures" },
  { latex: "\\overline{AB}", category: "Structures" },
  { latex: "\\triangle ABC", category: "Structures" },
  { latex: "\\overrightarrow{AB}", category: "Structures" },
  {
    latex: "\\underbrace{a + b + c}_{\\text{three terms}}",
    category: "Structures",
  },
  {
    latex: "\\overbrace{a + b + c}^{\\text{three terms}}",
    category: "Structures",
  },
  {
    latex: "\\begin{pmatrix} a & b \\\\ c & d \\end{pmatrix}",
    category: "Structures",
  },
  {
    latex: "\\begin{bmatrix} a & b \\\\ c & d \\end{bmatrix}",
    category: "Structures",
  },
  {
    latex: "\\begin{vmatrix} a & b \\\\ c & d \\end{vmatrix}",
    category: "Structures",
  },
  {
    latex:
      "\\begin{cases} x & \\text{if } x > 0 \\\\ -x & \\text{otherwise} \\end{cases}",
    category: "Structures",
  },

  // Logic and Set Theory (new category)
  { latex: "\\forall", category: "Logic and Set Theory" },
  { latex: "\\exists", category: "Logic and Set Theory" },
  { latex: "\\nexists", category: "Logic and Set Theory" },
  { latex: "\\neg", category: "Logic and Set Theory" },
  { latex: "\\lor", category: "Logic and Set Theory" },
  { latex: "\\land", category: "Logic and Set Theory" },
  { latex: "\\implies", category: "Logic and Set Theory" },
  { latex: "\\iff", category: "Logic and Set Theory" },
  { latex: "\\top", category: "Logic and Set Theory" },
  { latex: "\\bot", category: "Logic and Set Theory" },
  { latex: "\\varnothing", category: "Logic and Set Theory" },
  { latex: "\\mathbb{N}", category: "Logic and Set Theory" },
  { latex: "\\mathbb{Z}", category: "Logic and Set Theory" },
  { latex: "\\mathbb{Q}", category: "Logic and Set Theory" },
  { latex: "\\mathbb{R}", category: "Logic and Set Theory" },
  { latex: "\\mathbb{C}", category: "Logic and Set Theory" },
  { latex: "\\mathcal{P}", category: "Logic and Set Theory" },
  { latex: "\\subsetneq", category: "Logic and Set Theory" },
  { latex: "\\supsetneq", category: "Logic and Set Theory" },
  { latex: "\\complement", category: "Logic and Set Theory" },

  // Calculus and Analysis (new category)
  { latex: "\\lim_{x \\to a} f(x)", category: "Calculus and Analysis" },
  { latex: "\\liminf_{n \\to \\infty} x_n", category: "Calculus and Analysis" },
  { latex: "\\limsup_{n \\to \\infty} x_n", category: "Calculus and Analysis" },
  { latex: "\\oint_C f(z) \\, dz", category: "Calculus and Analysis" },
  { latex: "\\iint_D f(x,y) \\, dxdy", category: "Calculus and Analysis" },
  { latex: "\\iiint_E f(x,y,z) \\, dxdydz", category: "Calculus and Analysis" },
  {
    latex: "\\idotsint_V f(x_1,\\ldots,x_n) \\, dx_1 \\cdots dx_n",
    category: "Calculus and Analysis",
  },
  { latex: "\\frac{df}{dx}", category: "Calculus and Analysis" },
  {
    latex: "\\frac{\\partial f}{\\partial x}",
    category: "Calculus and Analysis",
  },
  { latex: "\\nabla f", category: "Calculus and Analysis" },
  { latex: "\\Delta f", category: "Calculus and Analysis" },
  { latex: "\\nabla \\cdot \\mathbf{F}", category: "Calculus and Analysis" },
  { latex: "\\nabla \\times \\mathbf{F}", category: "Calculus and Analysis" },
  { latex: "\\mathrm{d}x", category: "Calculus and Analysis" },
  { latex: "\\mathrm{d}y", category: "Calculus and Analysis" },
  { latex: "\\oint", category: "Calculus and Analysis" },

  // Linear Algebra (new category)
  { latex: "\\mathbf{A}", category: "Linear Algebra" },
  { latex: "\\mathbf{v}", category: "Linear Algebra" },
  { latex: "\\mathbf{0}", category: "Linear Algebra" },
  { latex: "\\mathbf{I}", category: "Linear Algebra" },
  { latex: "\\det(A)", category: "Linear Algebra" },
  { latex: "\\operatorname{tr}(A)", category: "Linear Algebra" },
  { latex: "\\operatorname{rank}(A)", category: "Linear Algebra" },
  { latex: "\\operatorname{ker}(A)", category: "Linear Algebra" },
  { latex: "\\operatorname{im}(A)", category: "Linear Algebra" },
  {
    latex: "\\operatorname{span}(\\{\\mathbf{v}_1,\\ldots,\\mathbf{v}_n\\})",
    category: "Linear Algebra",
  },
  { latex: "\\dim(V)", category: "Linear Algebra" },
  { latex: "A^T", category: "Linear Algebra" },
  { latex: "A^*", category: "Linear Algebra" },
  { latex: "A^{-1}", category: "Linear Algebra" },
  { latex: "A^\\dagger", category: "Linear Algebra" },
  { latex: "\\| \\mathbf{v} \\|", category: "Linear Algebra" },
  {
    latex: "\\langle \\mathbf{u}, \\mathbf{v} \\rangle",
    category: "Linear Algebra",
  },
  { latex: "\\mathbf{u} \\otimes \\mathbf{v}", category: "Linear Algebra" },
  { latex: "\\oplus", category: "Linear Algebra" },
  { latex: "\\ominus", category: "Linear Algebra" },

  // Number Theory (new category)
  { latex: "a \\mid b", category: "Number Theory" },
  { latex: "a \\nmid b", category: "Number Theory" },
  { latex: "a \\equiv b \\pmod{n}", category: "Number Theory" },
  { latex: "a \\not\\equiv b \\pmod{n}", category: "Number Theory" },
  { latex: "\\gcd(a, b)", category: "Number Theory" },
  { latex: "\\operatorname{lcm}(a, b)", category: "Number Theory" },
  { latex: "\\phi(n)", category: "Number Theory" },
  { latex: "\\tau(n)", category: "Number Theory" },
  { latex: "\\sigma(n)", category: "Number Theory" },
  { latex: "\\pi(n)", category: "Number Theory" },
  { latex: "\\zeta(s)", category: "Number Theory" },
  { latex: "\\mathbb{P}", category: "Number Theory" },

  // Probability and Statistics (new category)
  { latex: "P(A)", category: "Probability and Statistics" },
  { latex: "P(A \\mid B)", category: "Probability and Statistics" },
  { latex: "E[X]", category: "Probability and Statistics" },
  { latex: "\\operatorname{Var}(X)", category: "Probability and Statistics" },
  { latex: "\\sigma_X", category: "Probability and Statistics" },
  {
    latex: "\\operatorname{Cov}(X, Y)",
    category: "Probability and Statistics",
  },
  {
    latex: "\\operatorname{Corr}(X, Y)",
    category: "Probability and Statistics",
  },
  {
    latex: "X \\sim \\mathcal{N}(\\mu, \\sigma^2)",
    category: "Probability and Statistics",
  },
  { latex: "\\chi^2", category: "Probability and Statistics" },
  { latex: "\\mathcal{U}(a, b)", category: "Probability and Statistics" },
  { latex: "\\mathcal{B}(n, p)", category: "Probability and Statistics" },
  { latex: "\\mathcal{P}(\\lambda)", category: "Probability and Statistics" },
  { latex: "\\hat{\\theta}", category: "Probability and Statistics" },
  { latex: "\\bar{x}", category: "Probability and Statistics" },
  { latex: "\\tilde{x}", category: "Probability and Statistics" },

  // Miscellaneous Symbols (new category)
  { latex: "\\S", category: "Miscellaneous Symbols" },
  { latex: "\\P", category: "Miscellaneous Symbols" },
  { latex: "\\dag", category: "Miscellaneous Symbols" },
  { latex: "\\ddag", category: "Miscellaneous Symbols" },
  { latex: "\\copyright", category: "Miscellaneous Symbols" },
  { latex: "\\textregistered", category: "Miscellaneous Symbols" },
  { latex: "\\texttrademark", category: "Miscellaneous Symbols" },
  { latex: "\\ldots", category: "Miscellaneous Symbols" },
  { latex: "\\cdots", category: "Miscellaneous Symbols" },
  { latex: "\\vdots", category: "Miscellaneous Symbols" },
  { latex: "\\ddots", category: "Miscellaneous Symbols" },
  { latex: "\\#", category: "Miscellaneous Symbols" },
  { latex: "\\%", category: "Miscellaneous Symbols" },
  { latex: "\\&", category: "Miscellaneous Symbols" },
  { latex: "\\_", category: "Miscellaneous Symbols" },
  { latex: "\\|", category: "Miscellaneous Symbols" },
  { latex: "\\backslash", category: "Miscellaneous Symbols" },
];
